resources:
  - name: repo
    type: git
    source:
      uri: https://github.com/diazmaria/React-Blog.git
      branch: main
jobs:
  - name: unit-tests
    serial_groups:
      - blog-pipeline
    public: true
    plan:
      - get: repo
        trigger: true
      - task: unit-tests
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: { repository: node }
          inputs:
            - name: repo
          run:
            path: sh
            args:
              - "-exc"
              - |-
                cd repo
                yarn
                yarn test
  - name: build
    serial_groups:
      - blog-pipeline
    public: true
    plan:
      - get: repo
        passed: [unit-tests]
        trigger: true
      - task: build
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: { repository: node }
          inputs:
            - name: repo
          run:
            path: sh
            args:
              - "-exc"
              - |-
                cd repo
                yarn
                yarn build
  - name: deploy
    serial_groups:
      - blog-pipeline
    public: true
    plan:
      - get: repo
        passed: [build]
        trigger: true
      - task: deploy
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: { repository: node }
          inputs:
            - name: repo
          run:
            path: sh
            args:
              - "-exc"
              - |-
                echo deploying app now.... work in progress
