resources:
  - name: git-repo
    type: git
    icon: github
    source:
      uri: https://github.com/diazmaria/upskilling-project.git
      branch: main
jobs:
  - name: unit-tests
    plan:
      - get: git-repo
        trigger: true
      - task: unit-tests
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: { repository: node }
          inputs:
            - name: git-repo
          run:
            path: sh
            args:
              - "-exc"
              - |
                cd git-repo
                yarn install --silent
                yarn test
  - name: build
    plan:
      - get: git-repo
        passed: [unit-tests]
        trigger: true
      - task: build
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: { repository: node }
          inputs:
            - name: git-repo
          run:
            path: sh
            args:
              - "-exc"
              - |
                cd git-repo
                yarn install --silent
                yarn build
  - name: deploy
    public: true
    plan:
      - get: git-repo
        passed: [build]
        trigger: true
      - task: deploy
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: { repository: node }
          inputs:
            - name: git-repo
          run:
            path: sh
            args:
              - "-exc"
              - |
                echo Deploying application...🎉
